/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Ui;

/**
 *
 * @author keerthanaakannan
 */
public class HospitalAdmin extends javax.swing.JPanel {

    /**
     * Creates new form HospitalAdmin
     */
    public HospitalAdmin() {
        initComponents();
        checkupButton.setVisible(false);
         mortuaryButton.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        hospitalSplitPane = new javax.swing.JSplitPane();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        HospYesButton = new javax.swing.JRadioButton();
        HospNoButton = new javax.swing.JRadioButton();
        checkupButton = new javax.swing.JButton();
        mortuaryButton = new javax.swing.JButton();

        jPanel1.setBackground(new java.awt.Color(2, 33, 105));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 688, Short.MAX_VALUE)
        );

        hospitalSplitPane.setLeftComponent(jPanel1);

        jPanel2.setName(""); // NOI18N
        jPanel2.setPreferredSize(new java.awt.Dimension(1822, 797));

        jLabel1.setFont(new java.awt.Font("Helvetica Neue", 1, 24)); // NOI18N
        jLabel1.setText("HOSPITAL");

        jLabel2.setText("Is the patient alive?");

        HospYesButton.setText("Yes");
        HospYesButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HospYesButtonActionPerformed(evt);
            }
        });

        HospNoButton.setText("No");
        HospNoButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HospNoButtonActionPerformed(evt);
            }
        });

        checkupButton.setText("Checkup");
        checkupButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkupButtonActionPerformed(evt);
            }
        });

        mortuaryButton.setText("Mortuary");
        mortuaryButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mortuaryButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(248, 248, 248)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel1)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(78, 78, 78)
                                .addComponent(HospYesButton)))
                        .addGap(56, 56, 56)
                        .addComponent(HospNoButton))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(370, 370, 370)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(mortuaryButton)
                            .addComponent(checkupButton))))
                .addContainerGap(400, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabel1)
                .addGap(88, 88, 88)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(HospYesButton)
                    .addComponent(HospNoButton))
                .addGap(88, 88, 88)
                .addComponent(checkupButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(mortuaryButton)
                .addContainerGap(376, Short.MAX_VALUE))
        );

        hospitalSplitPane.setRightComponent(jPanel2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(hospitalSplitPane, javax.swing.GroupLayout.DEFAULT_SIZE, 1085, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(hospitalSplitPane, javax.swing.GroupLayout.DEFAULT_SIZE, 688, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void HospNoButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HospNoButtonActionPerformed
        // TODO add your handling code here:
        checkupButton.setVisible(false);
        HospYesButton.setSelected(false);
        mortuaryButton.setVisible(true);
        
    }//GEN-LAST:event_HospNoButtonActionPerformed

    private void HospYesButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HospYesButtonActionPerformed
        // TODO add your handling code here:
        mortuaryButton.setVisible(false);
        checkupButton.setVisible(true);
        HospNoButton.setSelected(false);
    }//GEN-LAST:event_HospYesButtonActionPerformed

    private void checkupButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkupButtonActionPerformed
        // TODO add your handling code here:
        CheckupAdminPanel checkPanel = new CheckupAdminPanel();
        hospitalSplitPane.setRightComponent(checkPanel);
    }//GEN-LAST:event_checkupButtonActionPerformed

    private void mortuaryButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mortuaryButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mortuaryButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton HospNoButton;
    private javax.swing.JRadioButton HospYesButton;
    private javax.swing.JButton checkupButton;
    private javax.swing.JSplitPane hospitalSplitPane;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JButton mortuaryButton;
    // End of variables declaration//GEN-END:variables
}
