/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Ui.UserandPoliceUI;

/**
 *
 * @author keerthanaakannan
 */
public class CreateandViewPolice extends javax.swing.JPanel {

    /**
     * Creates new form CreateandViewPolice
     */
    public CreateandViewPolice() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        PoliceListTable = new javax.swing.JTable();
        jLabel5 = new javax.swing.JLabel();
        policeID = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        policeDesignation = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        policeName = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        policeEmail = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        policeDepartment = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        policePhone = new javax.swing.JTextField();
        policeAdd = new javax.swing.JButton();
        policeUpdate = new javax.swing.JButton();
        policeDelete = new javax.swing.JButton();

        PoliceListTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Name", "Email", "Phone", "Designation", "Department"
            }
        ));
        jScrollPane1.setViewportView(PoliceListTable);

        jLabel5.setBackground(new java.awt.Color(2, 5, 105));
        jLabel5.setText("ID:");

        policeID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                policeIDActionPerformed(evt);
            }
        });

        jLabel7.setText("Designation");

        policeDesignation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                policeDesignationActionPerformed(evt);
            }
        });

        jLabel3.setForeground(new java.awt.Color(2, 5, 105));
        jLabel3.setText("Name:");

        policeName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                policeNameActionPerformed(evt);
            }
        });

        jLabel6.setForeground(new java.awt.Color(2, 5, 105));
        jLabel6.setText("Email:");

        policeEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                policeEmailActionPerformed(evt);
            }
        });

        jLabel8.setText("Department");

        policeDepartment.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                policeDepartmentActionPerformed(evt);
            }
        });

        jLabel4.setForeground(new java.awt.Color(2, 5, 105));
        jLabel4.setText("Phone:");

        policePhone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                policePhoneActionPerformed(evt);
            }
        });

        policeAdd.setBackground(new java.awt.Color(2, 33, 105));
        policeAdd.setForeground(new java.awt.Color(255, 255, 255));
        policeAdd.setText("Add");

        policeUpdate.setBackground(new java.awt.Color(2, 33, 105));
        policeUpdate.setForeground(new java.awt.Color(255, 255, 255));
        policeUpdate.setText("Update");

        policeDelete.setBackground(new java.awt.Color(2, 33, 105));
        policeDelete.setForeground(new java.awt.Color(255, 255, 255));
        policeDelete.setText("Delete");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(policeAdd)
                .addGap(66, 66, 66)
                .addComponent(policeUpdate)
                .addGap(75, 75, 75)
                .addComponent(policeDelete)
                .addGap(240, 240, 240))
            .addGroup(layout.createSequentialGroup()
                .addGap(155, 155, 155)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 502, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(170, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(204, 204, 204)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jLabel6)
                        .addComponent(jLabel5)
                        .addComponent(jLabel3))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(policeEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(policeName, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(policeID, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addComponent(jLabel7)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(policeDesignation, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel8)
                                .addComponent(jLabel4))
                            .addGap(18, 18, 18)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(policeDepartment, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(policePhone, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addContainerGap(257, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(76, 76, 76)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 229, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(policeDelete)
                    .addComponent(policeUpdate)
                    .addComponent(policeAdd))
                .addGap(118, 118, 118))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap(317, Short.MAX_VALUE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(policeID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel5)
                        .addComponent(policeDesignation, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel7))
                    .addGap(27, 27, 27)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(policeName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel3)
                        .addComponent(policeDepartment, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel8))
                    .addGap(27, 27, 27)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(policeEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(policePhone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addComponent(jLabel6))
                    .addGap(191, 191, 191)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void policeIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_policeIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_policeIDActionPerformed

    private void policeDesignationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_policeDesignationActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_policeDesignationActionPerformed

    private void policeNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_policeNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_policeNameActionPerformed

    private void policeEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_policeEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_policeEmailActionPerformed

    private void policeDepartmentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_policeDepartmentActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_policeDepartmentActionPerformed

    private void policePhoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_policePhoneActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_policePhoneActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable PoliceListTable;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton policeAdd;
    private javax.swing.JButton policeDelete;
    private javax.swing.JTextField policeDepartment;
    private javax.swing.JTextField policeDesignation;
    private javax.swing.JTextField policeEmail;
    private javax.swing.JTextField policeID;
    private javax.swing.JTextField policeName;
    private javax.swing.JTextField policePhone;
    private javax.swing.JButton policeUpdate;
    // End of variables declaration//GEN-END:variables
}
