/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Ui.UserandPoliceUI;

import Ui.UserandPoliceUI.CreateandViewPolice;
import Ui.UserandPoliceUI.ViewPoliceCaseJPanel;
import Ui.UserandPoliceUI.CreateCaseJPanel;

/**
 *
 * @author aniruddhasainkar
 */
public class PoliceJPanel extends javax.swing.JPanel {

    /**
     * Creates new form PoliceJPanel
     */
    public PoliceJPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Policepane = new javax.swing.JSplitPane();
        jPanel1 = new javax.swing.JPanel();
        btnCreatecaseuser = new javax.swing.JButton();
        btnViewcasepolice = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();

        jPanel1.setBackground(new java.awt.Color(2, 33, 105));

        btnCreatecaseuser.setText("Create Case");
        btnCreatecaseuser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreatecaseuserActionPerformed(evt);
            }
        });

        btnViewcasepolice.setText("View Case");
        btnViewcasepolice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewcasepoliceActionPerformed(evt);
            }
        });

        jButton1.setText("Add Police");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnCreatecaseuser, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnViewcasepolice, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addComponent(btnCreatecaseuser)
                .addGap(29, 29, 29)
                .addComponent(btnViewcasepolice)
                .addGap(99, 99, 99)
                .addComponent(jButton1)
                .addContainerGap(218, Short.MAX_VALUE))
        );

        Policepane.setLeftComponent(jPanel1);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 566, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 468, Short.MAX_VALUE)
        );

        Policepane.setRightComponent(jPanel3);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Policepane)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Policepane)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnCreatecaseuserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreatecaseuserActionPerformed
        // TODO add your handling code here:
        // TODO add your handling code here:
        CreateCaseJPanel createPanel = new CreateCaseJPanel();
        Policepane.setRightComponent(createPanel);
    }//GEN-LAST:event_btnCreatecaseuserActionPerformed

    private void btnViewcasepoliceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewcasepoliceActionPerformed
        // TODO add your handling code here:
        ViewPoliceCaseJPanel viewpolicePanel=new ViewPoliceCaseJPanel();
        Policepane.setRightComponent(viewpolicePanel);
    }//GEN-LAST:event_btnViewcasepoliceActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        CreateandViewPolice addpolice=new CreateandViewPolice();
        Policepane.setRightComponent(addpolice);
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JSplitPane Policepane;
    private javax.swing.JButton btnCreatecaseuser;
    private javax.swing.JButton btnViewcasepolice;
    private javax.swing.JButton jButton1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    // End of variables declaration//GEN-END:variables
}
