/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Ui.UserandPoliceUI;

import Model.Case;
import Model.CaseDirectory;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author aniruddhasainkar
 */
public class ViewPoliceCaseJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ViewPoliceCaseJPanel
     */
     CaseDirectory caseList=new CaseDirectory();
     
   
    
   public ViewPoliceCaseJPanel() {
        initComponents();
          populateTable();
   }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblCases = new javax.swing.JTable();
        btnBack = new javax.swing.JButton();

        tblCases.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Case ID", "Name", "Age", "Email ", "Phone No", "Case Type", "Status"
            }
        ));
        jScrollPane1.setViewportView(tblCases);

        btnBack.setText("Back");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(82, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnBack)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 526, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(77, 77, 77))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(76, 76, 76)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addComponent(btnBack)
                .addContainerGap(137, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblCases;
    // End of variables declaration//GEN-END:variables

 private void populateTable() {
        
        DefaultTableModel model = (DefaultTableModel) tblCases.getModel();
        
        model.setRowCount(0);
        
        for (Case vs :caseList.displayCase()){
            
            Object[] row = new Object[4];
            
            row[0]=vs.getCaseID();
            row[1]=vs.getName();
            row[2]=vs.getAge();
            row[3]=vs.getEmail();
            row[4]=vs.getPhone();
            row[5]=vs.getCaseType();
            row[6]=vs.getStatus();
           
            
            
            model.addRow(row);
            
            
        }
        
        

    }

    

    private void addRow(Object[] row) {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }
}
