/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Ui.InvestigationUI;

import Ui.HospitalAdmin;
import Ui.IndividualProfileUI.ViewVictimEvidenceJPanel;
import java.awt.CardLayout;

/**
 *
 * @author aniruddhasainkar
 */
public class InvestigationSummaryJPanel extends javax.swing.JPanel {

    /**
     * Creates new form InvestigationSummaryJPanel
     */
    public InvestigationSummaryJPanel() {
        initComponents();
         uploadEvidenceLabel.setVisible(false);
        uploadButton.setVisible(false);
        addInfoLabel.setVisible(false);
        addInfoText.setVisible(false);
        caseTypeLabel.setVisible(false);
        criminalButton.setVisible(false);
        civilButton.setVisible(false);
        corpButton.setVisible(false);
        updateButton.setVisible(false);
        medReqlabel.setVisible(false);
        MedicalButton.setVisible(false);
        addInfoScrollPane.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        invContainer = new javax.swing.JPanel();
        investigationSummary = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        uploadEvidenceLabel = new javax.swing.JLabel();
        uploadButton = new javax.swing.JButton();
        addInfoScrollPane = new javax.swing.JScrollPane();
        addInfoText = new javax.swing.JTextArea();
        addInfoLabel = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        caseValidYesButton = new javax.swing.JRadioButton();
        medReqlabel = new javax.swing.JLabel();
        caseValidNoButton = new javax.swing.JRadioButton();
        caseTypeLabel = new javax.swing.JLabel();
        corpButton = new javax.swing.JRadioButton();
        criminalButton = new javax.swing.JRadioButton();
        updateButton = new javax.swing.JButton();
        civilButton = new javax.swing.JRadioButton();
        MedicalButton = new javax.swing.JButton();

        invContainer.setLayout(new java.awt.CardLayout());

        investigationSummary.setName(""); // NOI18N
        investigationSummary.setPreferredSize(new java.awt.Dimension(1822, 797));

        jLabel2.setFont(new java.awt.Font("Helvetica Neue", 1, 24)); // NOI18N
        jLabel2.setText("Investigation Summary");

        uploadEvidenceLabel.setText("Upload Evidence:");

        uploadButton.setText("Upload");
        uploadButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                uploadButtonActionPerformed(evt);
            }
        });

        addInfoText.setColumns(20);
        addInfoText.setRows(5);
        addInfoScrollPane.setViewportView(addInfoText);

        addInfoLabel.setText("Additional Info");

        jLabel10.setText(" Case Valid:");

        caseValidYesButton.setText("Yes");
        caseValidYesButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                caseValidYesButtonActionPerformed(evt);
            }
        });

        medReqlabel.setText("Medical ");

        caseValidNoButton.setText("No");
        caseValidNoButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                caseValidNoButtonActionPerformed(evt);
            }
        });

        caseTypeLabel.setText("Type of Case:");

        corpButton.setText("Corporate");
        corpButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                corpButtonActionPerformed(evt);
            }
        });

        criminalButton.setText("Criminal");
        criminalButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                criminalButtonActionPerformed(evt);
            }
        });

        updateButton.setText("Update");

        civilButton.setText("Civil");
        civilButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                civilButtonActionPerformed(evt);
            }
        });

        MedicalButton.setText("Take Medical");
        MedicalButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MedicalButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout investigationSummaryLayout = new javax.swing.GroupLayout(investigationSummary);
        investigationSummary.setLayout(investigationSummaryLayout);
        investigationSummaryLayout.setHorizontalGroup(
            investigationSummaryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(investigationSummaryLayout.createSequentialGroup()
                .addGap(414, 414, 414)
                .addGroup(investigationSummaryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel2)
                    .addGroup(investigationSummaryLayout.createSequentialGroup()
                        .addGroup(investigationSummaryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(updateButton)
                            .addGroup(investigationSummaryLayout.createSequentialGroup()
                                .addComponent(jLabel10)
                                .addGap(71, 71, 71)
                                .addComponent(caseValidYesButton)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(caseValidNoButton)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(investigationSummaryLayout.createSequentialGroup()
                .addGap(157, 157, 157)
                .addGroup(investigationSummaryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(uploadEvidenceLabel)
                    .addComponent(addInfoLabel))
                .addGap(33, 33, 33)
                .addGroup(investigationSummaryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(investigationSummaryLayout.createSequentialGroup()
                        .addComponent(uploadButton)
                        .addGap(311, 311, 311)
                        .addComponent(caseTypeLabel))
                    .addGroup(investigationSummaryLayout.createSequentialGroup()
                        .addComponent(addInfoScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(medReqlabel)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(investigationSummaryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(investigationSummaryLayout.createSequentialGroup()
                        .addComponent(criminalButton)
                        .addGap(18, 18, 18)
                        .addComponent(civilButton))
                    .addComponent(MedicalButton))
                .addGap(18, 18, 18)
                .addComponent(corpButton)
                .addGap(0, 97, Short.MAX_VALUE))
        );
        investigationSummaryLayout.setVerticalGroup(
            investigationSummaryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(investigationSummaryLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel2)
                .addGap(29, 29, 29)
                .addGroup(investigationSummaryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(caseValidYesButton)
                    .addComponent(caseValidNoButton))
                .addGap(41, 41, 41)
                .addGroup(investigationSummaryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(uploadEvidenceLabel)
                    .addComponent(uploadButton)
                    .addComponent(caseTypeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(criminalButton)
                    .addComponent(civilButton)
                    .addComponent(corpButton))
                .addGap(49, 49, 49)
                .addGroup(investigationSummaryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(addInfoLabel)
                    .addComponent(addInfoScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(investigationSummaryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(medReqlabel, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(MedicalButton)))
                .addGap(66, 66, 66)
                .addComponent(updateButton)
                .addContainerGap(326, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(investigationSummary, javax.swing.GroupLayout.PREFERRED_SIZE, 1102, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(21, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addComponent(invContainer, javax.swing.GroupLayout.PREFERRED_SIZE, 1097, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 32, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(investigationSummary, javax.swing.GroupLayout.DEFAULT_SIZE, 729, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addComponent(invContainer, javax.swing.GroupLayout.PREFERRED_SIZE, 717, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 18, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void uploadButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_uploadButtonActionPerformed
        // TODO add your handling code here:\
         ViewVictimEvidenceJPanel vicMed = new ViewVictimEvidenceJPanel ();
         invContainer.add("ManageInvestigationSummary", vicMed);
        CardLayout layout = (CardLayout) invContainer.getLayout();
        layout.next(invContainer);
        investigationSummary.setVisible(false);     
    }//GEN-LAST:event_uploadButtonActionPerformed

    private void corpButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_corpButtonActionPerformed
        // TODO add your handling code here:
        medReqlabel.setVisible(false);
        MedicalButton.setVisible(false);
    }//GEN-LAST:event_corpButtonActionPerformed

    private void civilButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_civilButtonActionPerformed
        // TODO add your handling code here:
        medReqlabel.setVisible(false);
        MedicalButton.setVisible(false);
    }//GEN-LAST:event_civilButtonActionPerformed

    private void criminalButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_criminalButtonActionPerformed
        // TODO add your handling code here:
        medReqlabel.setVisible(true);
        MedicalButton.setVisible(true);
    }//GEN-LAST:event_criminalButtonActionPerformed

    private void caseValidNoButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_caseValidNoButtonActionPerformed
        // TODO add your handling code here:
        caseValidYesButton.setSelected(false);
        uploadEvidenceLabel.setVisible(false);
        uploadButton.setVisible(false);
        addInfoLabel.setVisible(false);
        addInfoText.setVisible(false);
        caseTypeLabel.setVisible(false);
        criminalButton.setVisible(false);
        civilButton.setVisible(false);
        corpButton.setVisible(false);
        updateButton.setVisible(false);
        //addInfoText.setVisible(false);
        medReqlabel.setVisible(false);
        MedicalButton.setVisible(false);
        addInfoScrollPane.setVisible(false);
    }//GEN-LAST:event_caseValidNoButtonActionPerformed

    private void caseValidYesButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_caseValidYesButtonActionPerformed
        // TODO add your handling code here:
        caseValidNoButton.setSelected(false);
        uploadEvidenceLabel.setVisible(true);
        uploadButton.setVisible(true);
        addInfoLabel.setVisible(true);
        addInfoText.setVisible(true);
        caseTypeLabel.setVisible(true);
        criminalButton.setVisible(true);
        civilButton.setVisible(true);
        corpButton.setVisible(true);
        updateButton.setVisible(true);
        addInfoText.setVisible(true);
        medReqlabel.setVisible(false);
         MedicalButton.setVisible(false);
        addInfoScrollPane.setVisible(true);
    }//GEN-LAST:event_caseValidYesButtonActionPerformed

    private void MedicalButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MedicalButtonActionPerformed
        // TODO add your handling code here:
       
        HospitalAdmin hosp = new HospitalAdmin();
        invContainer.add("ManageEnterpriseJPanel", hosp);
        CardLayout layout = (CardLayout) invContainer.getLayout();
        layout.next(invContainer);
        investigationSummary.setVisible(false);   
        invContainer.setVisible(true);
        
    }//GEN-LAST:event_MedicalButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton MedicalButton;
    private javax.swing.JLabel addInfoLabel;
    private javax.swing.JScrollPane addInfoScrollPane;
    private javax.swing.JTextArea addInfoText;
    private javax.swing.JLabel caseTypeLabel;
    private javax.swing.JRadioButton caseValidNoButton;
    private javax.swing.JRadioButton caseValidYesButton;
    private javax.swing.JRadioButton civilButton;
    private javax.swing.JRadioButton corpButton;
    private javax.swing.JRadioButton criminalButton;
    private javax.swing.JPanel invContainer;
    private javax.swing.JPanel investigationSummary;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel medReqlabel;
    private javax.swing.JButton updateButton;
    private javax.swing.JButton uploadButton;
    private javax.swing.JLabel uploadEvidenceLabel;
    // End of variables declaration//GEN-END:variables
}
